import * as icon from './iconlist.js'

const mime = [
    {name:"application/vnd.lotus-1-2-3", icon:'' },
    {name:"text/vnd.in3d.3dml", icon:'' },
    {name:"video/3gpp2", icon: icon.__video },
    {name:"image/avif", icon: icon.__image},
    {name:"application/x-krita", icon:'' },
    {name:"image/heic", icon: icon.__image },
    {name:"video/3gpp", icon: icon.__video },
    {name:"audio/3gpp2", icon: icon.__audio },
    {name:"audio/3gpp", icon: icon.__audio },
    {name:"application/x-7z-compressed", icon: icon.__archive },
    {name:"application/octet-stream", icon:icon.__octetStream },
    {name:"application/x-authorware-bin", icon:'' },
    {name:"audio/x-aac", icon: icon.__audio },
    {name:"application/x-authorware-map", icon:'' },
    {name:"application/x-authorware-seg", icon:'' },
    {name:"application/x-abiword", icon: icon.__document },
    {name:"application/vnd.americandynamics.acc", icon:'' },
    {name:"application/x-ace-compressed", icon: icon.__archive },
    {name:"application/vnd.acucobol", icon:'' },
    {name:"application/vnd.acucorp", icon:'' },
    {name:"audio/adpcm", icon: icon.__audio },
    {name:"application/vnd.audiograph", icon:'' },
    {name:"application/x-font-type1", icon:'' },
    {name:"application/vnd.ibm.modcap", icon:'' },
    {name:"application/postscript", icon:'' },
    {name:"audio/x-aiff", icon: icon.__audio },
    {name:"application/vnd.adobe.air-application-installer-package+zip", icon: icon.__archive },
    {name:"application/vnd.amiga.ami", icon:'' },
    {name:"application/vnd.android.package-archive", icon: icon.__archive },
    {name:"application/x-ms-application", icon:'' },
    {name:"application/vnd.lotus-approach", icon:'' },
    {name:"application/pgp-signature", icon:'' },
    {name:"video/x-ms-asf", icon: icon.__video },
    {name:"text/x-asm", icon:'' },
    {name:"application/vnd.accpac.simply.aso", icon:'' },
    {name:"application/atom+xml", icon:'' },
    {name:"application/atomcat+xml", icon:'' },
    {name:"application/atomsvc+xml", icon:'' },
    {name:"application/vnd.antix.game-component", icon:'' },
    {name:"audio/basic", icon: icon.__audio },
    {name:"video/x-msvideo", icon: icon.__video },
    {name:"application/applixware", icon:'' },
    {name:"application/vnd.airzip.filesecure.azf", icon: icon.__archive },
    {name:"application/vnd.airzip.filesecure.azs", icon: icon.__archive },
    {name:"application/vnd.amazon.ebook", icon:'' },
    {name:"application/x-msdownload", icon:'' },
    {name:"application/x-bcpio", icon:'' },
    {name:"application/x-font-bdf", icon:'' },
    {name:"application/vnd.syncml.dm+wbxml", icon:'' },
    {name:"application/vnd.fujitsu.oasysprs", icon:'' },
    {name:"application/vnd.bmi", icon:'' },
    {name:"image/bmp", icon: icon.__image },
    {name:"application/vnd.framemaker", icon:'' },
    {name:"application/vnd.previewsystems.box", icon:'' },
    {name:"application/x-bzip2", icon: icon.__archive },
    {name:"image/prs.btif", icon: icon.__image },
    {name:"application/x-bzip", icon: icon.__archive },
    {name:"text/x-c", icon:'' },
    {name:"application/vnd.clonk.c4group", icon:'' },
    {name:"application/vnd.ms-cab-compressed", icon: icon.__archive },
    {name:"application/vnd.curl.car", icon:'' },
    {name:"application/vnd.ms-pki.seccat", icon:'' },
    {name:"application/x-director", icon:'' },
    {name:"application/ccxml+xml", icon:'' },
    {name:"application/vnd.contact.cmsg", icon:'' },
    {name:"application/x-netcdf", icon:'' },
    {name:"application/vnd.mediastation.cdkey", icon:'' },
    {name:"chemical/x-cdx", icon:'' },
    {name:"application/vnd.chemdraw+xml", icon:'' },
    {name:"application/vnd.cinderella", icon:'' },
    {name:"application/pkix-cert", icon:'' },
    {name:"image/cgm", icon: icon.__image },
    {name:"application/x-chat", icon:'' },
    {name:"application/vnd.ms-htmlhelp", icon:'' },
    {name:"application/vnd.kde.kchart", icon:'' },
    {name:"chemical/x-cif", icon:'' },
    {name:"application/vnd.anser-web-certificate-issue-initiation", icon:'' },
    {name:"application/vnd.ms-artgalry", icon:'' },
    {name:"application/vnd.claymore", icon:'' },
    {name:"application/java-vm", icon:'' },
    {name:"application/vnd.crick.clicker.keyboard", icon:'' },
    {name:"application/vnd.crick.clicker.palette", icon:'' },
    {name:"application/vnd.crick.clicker.template", icon:'' },
    {name:"application/vnd.crick.clicker.wordbank", icon: icon.__document },
    {name:"application/vnd.crick.clicker", icon:'' },
    {name:"application/x-msclip", icon:'' },
    {name:"application/vnd.cosmocaller", icon:'' },
    {name:"chemical/x-cmdf", icon:'' },
    {name:"chemical/x-cml", icon:'' },
    {name:"application/vnd.yellowriver-custom-menu", icon:'' },
    {name:"image/x-cmx", icon: icon.__image },
    {name:"application/vnd.rim.cod", icon:'' },
    {name:"text/plain", icon: icon.__document },
    {name:"application/vnd.debian.binary-package", icon:'' },
    {name:"text/markdown", icon:'' },
    {name:"text/x-markdown", icon:'' },
    {name:"application/x-cpio", icon:'' },
    {name:"application/mac-compactpro", icon:'' },
    {name:"application/x-mscardfile", icon:'' },
    {name:"application/pkix-crl", icon:'' },
    {name:"application/x-x509-ca-cert", icon:'' },
    {name:"application/x-csh", icon:'' },
    {name:"chemical/x-csml", icon:'' },
    {name:"application/vnd.commonspace", icon:'' },
    {name:"text/css", icon:'' },
    {name:"text/csv", icon:'' },
    {name:"application/cu-seeme", icon:'' },
    {name:"text/vnd.curl", icon:'' },
    {name:"application/prs.cww", icon:'' },
    {name:"application/vnd.mobius.daf", icon:'' },
    {name:"application/vnd.fdsn.seed", icon:'' },
    {name:"application/davmount+xml", icon:'' },
    {name:"text/vnd.curl.dcurl", icon:'' },
    {name:"application/vnd.oma.dd2+xml", icon:'' },
    {name:"application/vnd.fujixerox.ddd", icon:'' },
    {name:"application/x-debian-package", icon:'' },
    {name:"application/vnd.dreamfactory", icon:'' },
    {name:"application/vnd.mobius.dis", icon:'' },
    {name:"image/vnd.djvu", icon: icon.__image },
    {name:"application/vnd.dna", icon:'' },
    {name:"application/msword", icon: icon.__document },
    {name:"application/vnd.ms-word.document.macroenabled.12", icon: icon.__document },
    {name:"application/vnd.openxmlformats-officedocument.wordprocessingml.document", icon: icon.__document },
    {name:"application/vnd.ms-word.template.macroenabled.12", icon: icon.__document },
    {name:"application/vnd.openxmlformats-officedocument.wordprocessingml.template", icon: icon.__document },
    {name:"application/vnd.osgi.dp", icon:'' },
    {name:"application/vnd.dpgraph", icon:'' },
    {name:"text/prs.lines.tag", icon:'' },
    {name:"application/x-dtbook+xml", icon:'' },
    {name:"application/xml-dtd", icon:'' },
    {name:"audio/vnd.dts", icon: icon.__audio },
    {name:"audio/vnd.dts.hd", icon: icon.__audio },
    {name:"application/x-dvi", icon:'' },
    {name:"model/vnd.dwf", icon:'' },
    {name:"image/vnd.dwg", icon: icon.__image },
    {name:"image/vnd.dxf", icon: icon.__image },
    {name:"application/vnd.spotfire.dxp", icon:'' },
    {name:"audio/vnd.nuera.ecelp4800", icon: icon.__audio },
    {name:"audio/vnd.nuera.ecelp7470", icon: icon.__audio },
    {name:"audio/vnd.nuera.ecelp9600", icon: icon.__audio },
    {name:"application/ecmascript", icon:'' },
    {name:"application/vnd.novadigm.edm", icon:'' },
    {name:"application/vnd.novadigm.edx", icon:'' },
    {name:"application/vnd.picsel", icon:'' },
    {name:"application/vnd.pg.osasli", icon:'' },
    {name:"message/rfc822", icon:'' },
    {name:"application/emma+xml", icon:'' },
    {name:"audio/vnd.digital-winds", icon: icon.__audio },
    {name:"application/vnd.ms-fontobject", icon:'' },
    {name:"application/epub+zip", icon: icon.__archive },
    {name:"application/vnd.eszigno3+xml", icon:'' },
    {name:"application/vnd.epson.esf", icon:'' },
    {name:"text/x-setext", icon:'' },
    {name:"application/vnd.novadigm.ext", icon:'' },
    {name:"application/andrew-inset", icon:'' },
    {name:"application/vnd.ezpix-album", icon:'' },
    {name:"application/vnd.ezpix-package", icon:'' },
    {name:"text/x-fortran", icon:'' },
    {name:"video/x-f4v", icon: icon.__video },
    {name:"image/vnd.fastbidsheet", icon: icon.__image },
    {name:"application/vnd.fdf", icon:'' },
    {name:"application/vnd.denovo.fcselayout-link", icon:'' },
    {name:"application/vnd.fujitsu.oasysgp", icon:'' },
    {name:"image/x-freehand", icon: icon.__image },
    {name:"application/x-xfig", icon:'' },
    {name:"video/x-fli", icon: icon.__video },
    {name:"application/vnd.micrografx.flo", icon:'' },
    {name:"video/x-flv", icon: icon.__video },
    {name:"application/vnd.kde.kivio", icon:'' },
    {name:"text/vnd.fmi.flexstor", icon:'' },
    {name:"text/vnd.fly", icon:'' },
    {name:"application/vnd.frogans.fnc", icon:'' },
    {name:"image/vnd.fpx", icon: icon.__image },
    {name:"application/vnd.fsc.weblaunch", icon:'' },
    {name:"image/vnd.fst", icon: icon.__image },
    {name:"application/vnd.fluxtime.clip", icon:'' },
    {name:"application/vnd.anser-web-funds-transfer-initiation", icon:'' },
    {name:"video/vnd.fvt", icon: icon.__video },
    {name:"application/vnd.fuzzysheet", icon:'' },
    {name:"image/g3fax", icon: icon.__image },
    {name:"application/vnd.groove-account", icon:'' },
    {name:"model/vnd.gdl", icon:'' },
    {name:"application/vnd.dynageo", icon:'' },
    {name:"application/vnd.geometry-explorer", icon:'' },
    {name:"application/vnd.geogebra.file", icon:'' },
    {name:"application/vnd.geogebra.tool", icon:'' },
    {name:"application/vnd.groove-help", icon:'' },
    {name:"image/gif", icon: icon.__image },
    {name:"application/vnd.groove-identity-message", icon:'' },
    {name:"application/vnd.gmx", icon:'' },
    {name:"application/x-gnumeric", icon:'' },
    {name:"application/vnd.flographit", icon:'' },
    {name:"application/vnd.grafeq", icon:'' },
    {name:"application/srgs", icon:'' },
    {name:"application/vnd.groove-injector", icon:'' },
    {name:"application/srgs+xml", icon:'' },
    {name:"application/x-font-ghostscript", icon:'' },
    {name:"application/x-gtar", icon: icon.__archive },
    {name:"application/vnd.groove-tool-message", icon:'' },
    {name:"model/vnd.gtw", icon:'' },
    {name:"text/vnd.graphviz", icon:'' },
    {name:"application/x-gzip", icon: icon.__archive },
    {name:"application/gzip", icon: icon.__archive },
    {name:"video/h261", icon: icon.__video },
    {name:"gcode", icon:'' },
    {name:"video/h263", icon: icon.__video },
    {name:"video/h264", icon: icon.__video },
    {name:"application/vnd.hbci", icon:'' },
    {name:"application/x-hdf", icon:'' },
    {name:"application/winhlp", icon:'' },
    {name:"application/vnd.hp-hpgl", icon:'' },
    {name:"application/vnd.hp-hpid", icon:'' },
    {name:"application/vnd.hp-hps", icon:'' },
    {name:"application/mac-binhex40", icon:'' },
    {name:"application/vnd.kenameaapp", icon:'' },
    {name:"text/html", icon:'' },
    {name:"application/vnd.yamaha.hv-dic", icon:'' },
    {name:"application/vnd.yamaha.hv-voice", icon:'' },
    {name:"application/vnd.yamaha.hv-script", icon:'' },
    {name:"application/vnd.iccprofile", icon:'' },
    {name:"x-conference/x-cooltalk", icon:'' },
    {name:"image/x-icon", icon: icon.__image },
    {name:"text/calendar", icon:'' },
    {name:"image/ief", icon: icon.__image },
    {name:"application/vnd.shana.informed.formdata", icon:'' },
    {name:"model/iges", icon:'' },
    {name:"application/vnd.igloader", icon:'' },
    {name:"application/vnd.micrografx.igx", icon:'' },
    {name:"application/vnd.shana.informed.interchange", icon:'' },
    {name:"application/vnd.accpac.simply.imp", icon:'' },
    {name:"application/vnd.ms-ims", icon:'' },
    {name:"application/vnd.shana.informed.package", icon:'' },
    {name:"application/vnd.ibm.rights-management", icon:'' },
    {name:"application/vnd.irepository.package+xml", icon:'' },
    {name:"application/vnd.shana.informed.formtemplate", icon:'' },
    {name:"application/vnd.immervision-ivp", icon:'' },
    {name:"application/vnd.immervision-ivu", icon:'' },
    {name:"text/vnd.sun.j2me.app-descriptor", icon:'' },
    {name:"application/vnd.jam", icon:'' },
    {name:"application/java-archive", icon: icon.__archive },
    {name:"text/x-java-source", icon:'' },
    {name:"application/vnd.jisp", icon:'' },
    {name:"application/vnd.hp-jlyt", icon:'' },
    {name:"application/x-java-jnlp-file", icon:'' },
    {name:"application/vnd.joost.joda-archive", icon: icon.__archive },
    {name:"image/jpeg", icon: icon.__image },
    {name:"image/pjpeg", icon: icon.__image },
    {name:"video/jpm", icon: icon.__video },
    {name:"video/jpeg", icon: icon.__video },
    {name:"application/x-trash", icon:'' },
    {name:"application/x-shellscript", icon:'' },
    {name:"text/javascript", icon:'' },
    {name:"application/json", icon:'' },
    {name:"text/json", icon:'' },
    {name:"audio/midi", icon: icon.__midi },
    {name:"audio/aiff", icon: icon.__audio },
    {name:"audio/opus", icon: icon.__audio },
    {name:"application/vnd.kde.karbon", icon:'' },
    {name:"application/vnd.kde.kformula", icon:'' },
    {name:"application/vnd.kidspiration", icon:'' },
    {name:"application/x-killustrator", icon:'' },
    {name:"application/vnd.google-earth.kml+xml", icon:'' },
    {name:"application/vnd.google-earth.kmz", icon:'' },
    {name:"application/vnd.kinar", icon:'' },
    {name:"application/vnd.kde.kontour", icon:'' },
    {name:"application/vnd.kde.kpresenter", icon:icon.__presentation },
    {name:"application/vnd.kde.kspread", icon:icon.__spreadsheet},
    {name:"application/vnd.kahootz", icon:'' },
    {name:"application/vnd.kde.kword", icon: icon.__document },
    {name:"application/x-latex", icon:'' },
    {name:"application/vnd.llamagraphics.life-balance.desktop", icon:'' },
    {name:"application/vnd.llamagraphics.life-balance.exchange+xml", icon:'' },
    {name:"application/vnd.hhe.lesson-player", icon:'' },
    {name:"application/vnd.route66.link66+xml", icon:'' },
    {name:"application/lost+xml", icon:'' },
    {name:"application/vnd.ms-lrm", icon:'' },
    {name:"application/vnd.frogans.ltf", icon:'' },
    {name:"audio/vnd.lucent.voice", icon: icon.__audio },
    {name:"application/vnd.lotus-wordpro", icon: icon.__document },
    {name:"application/x-msmediaview", icon:'' },
    {name:"video/mpeg", icon: icon.__video },
    {name:"audio/mpeg", icon: icon.__audio },
    {name:"audio/x-mpegurl", icon: icon.__audio },
    {name:"video/vnd.mpegurl", icon: icon.__video },
    {name:"video/x-m4v", icon: icon.__video },
    {name:"application/mathematica", icon:'' },
    {name:"application/vnd.ecowin.chart", icon:'' },
    {name:"text/troff", icon:'' },
    {name:"application/mathml+xml", icon:'' },
    {name:"text/mathml", icon:'' },
    {name:"application/vnd.sqlite3", icon: icon.__sql },
    {name:"application/x-sqlite3", icon: icon.__sql },
    {name:"application/vnd.mobius.mbk", icon:'' },
    {name:"application/mbox", icon:'' },
    {name:"application/vnd.medcalcdata", icon:'' },
    {name:"application/vnd.mcd", icon:'' },
    {name:"text/vnd.curl.mcurl", icon:'' },
    {name:"application/x-msaccess", icon:'' },
    {name:"image/vnd.ms-modi", icon: icon.__image },
    {name:"model/mesh", icon:'' },
    {name:"application/vnd.mfmp", icon:'' },
    {name:"application/vnd.proteus.magazine", icon:'' },
    {name:"application/vnd.mif", icon:'' },
    {name:"video/mj2", icon: icon.__video },
    {name:"application/vnd.dolby.mlp", icon:'' },
    {name:"application/vnd.chipnuts.karaoke-mmd", icon:'' },
    {name:"application/vnd.smaf", icon:'' },
    {name:"image/vnd.fujixerox.edmics-mmr", icon: icon.__image },
    {name:"application/x-msmoney", icon:'' },
    {name:"application/x-mobipocket-ebook", icon:'' },
    {name:"video/quicktime", icon: icon.__video },
    {name:"video/x-sgi-movie", icon: icon.__video },
    {name:"video/mp4", icon: icon.__video },
    {name:"audio/mp4", icon: icon.__audio },
    {name:"application/mp4", icon:'' },
    {name:"application/vnd.mophun.certificate", icon:'' },
    {name:"application/vnd.apple.installer+xml", icon:'' },
    {name:"application/vnd.blueice.multipass", icon:'' },
    {name:"application/vnd.mophun.application", icon:'' },
    {name:"application/vnd.ms-project", icon:'' },
    {name:"application/vnd.ibm.minipay", icon:'' },
    {name:"application/vnd.mobius.mqy", icon:'' },
    {name:"application/marc", icon:'' },
    {name:"application/mediaservercontrol+xml", icon:'' },
    {name:"application/vnd.fdsn.mseed", icon:'' },
    {name:"application/vnd.mseq", icon:'' },
    {name:"application/vnd.epson.msf", icon:'' },
    {name:"application/vnd.mobius.msl", icon:'' },
    {name:"application/vnd.muvee.style", icon:'' },
    {name:"model/vnd.mts", icon:'' },
    {name:"application/vnd.musician", icon:'' },
    {name:"application/vnd.recordare.musicxml+xml", icon:'' },
    {name:"application/vnd.mfer", icon:'' },
    {name:"application/mxf", icon:'' },
    {name:"application/vnd.recordare.musicxml", icon:'' },
    {name:"application/xv+xml", icon:'' },
    {name:"application/vnd.triscape.mxs", icon:'' },
    {name:"application/vnd.nokia.n-gage.symbian.install", icon:'' },
    {name:"application/x-dtbncx+xml", icon:'' },
    {name:"application/vnd.nokia.n-gage.data", icon:'' },
    {name:"application/vnd.neurolanguage.nlu", icon:'' },
    {name:"application/vnd.enliven", icon:'' },
    {name:"application/vnd.noblenet-directory", icon:'' },
    {name:"application/vnd.noblenet-sealer", icon:'' },
    {name:"application/vnd.noblenet-web", icon:'' },
    {name:"image/vnd.net-fpx", icon: icon.__image },
    {name:"application/vnd.lotus-notes", icon:'' },
    {name:"application/vnd.fujitsu.oasys2", icon:'' },
    {name:"application/vnd.fujitsu.oasys3", icon:'' },
    {name:"application/vnd.fujitsu.oasys", icon:'' },
    {name:"application/x-msbinder", icon:'' },
    {name:"application/oda", icon:'' },
    {name:"application/vnd.oasis.opendocument.database", icon: icon.__sql },
    {name:"application/vnd.oasis.opendocument.chart", icon: icon.__document },
    {name:"application/vnd.oasis.opendocument.formula", icon: icon.__document },
    {name:"application/vnd.oasis.opendocument.formula-template", icon: icon.__document },
    {name:"application/vnd.oasis.opendocument.graphics", icon: icon.__document },
    {name:"application/vnd.oasis.opendocument.image", icon: icon.__image },
    {name:"application/vnd.oasis.opendocument.presentation", icon: icon.__presentation },
    {name:"application/vnd.oasis.opendocument.spreadsheet", icon: icon.__spreadsheet },
    {name:"application/vnd.oasis.opendocument.text", icon: icon.__document },
    {name:"audio/ogg", icon: icon.__audio },
    {name:"video/x-matroska", icon: icon.__video },
    {name:"audio/x-matroska", icon: icon.__audio },
    {name:"video/ogg", icon: icon.__video },
    {name:"application/ogg", icon:'' },
    {name:"application/onenote", icon:'' },
    {name:"application/oebps-package+xml", icon:'' },
    {name:"application/vnd.palm", icon:'' },
    {name:"application/vnd.lotus-organizer", icon:'' },
    {name:"application/vnd.yamaha.openscoreformat", icon:'' },
    {name:"application/vnd.yamaha.openscoreformat.osfpvg+xml", icon:'' },
    {name:"application/vnd.oasis.opendocument.chart-template", icon: icon.__document },
    {name:"font/woff", icon:'' },
    {name:"font/woff2", icon:'' },
    {name:"application/x-redhat-package-manager", icon:'' },
    {name:"application/x-perl", icon:'' },
    {name:"audio/webm", icon: icon.__audio },
    {name:"video/webm", icon: icon.__video },
    {name:"image/webp", icon: icon.__image },
    {name:"application/x-font-otf", icon:'' },
    {name:"font/otf", icon:'' },
    {name:"application/vnd.oasis.opendocument.graphics-template", icon: icon.__document },
    {name:"application/vnd.oasis.opendocument.text-web", icon: icon.__document },
    {name:"application/vnd.oasis.opendocument.image-template", icon: icon.__image },
    {name:"application/vnd.oasis.opendocument.text-master", icon: icon.__document },
    {name:"application/vnd.oasis.opendocument.presentation-template", icon: icon.__presentation },
    {name:"application/vnd.oasis.opendocument.spreadsheet-template", icon: icon.__spreadsheet },
    {name:"application/vnd.oasis.opendocument.text-template", icon: icon.__document },
    {name:"application/vnd.openofficeorg.extension", icon:'' },
    {name:"text/x-pascal", icon:'' },
    {name:"application/pkcs10", icon:'' },
    {name:"application/x-pkcs12", icon:'' },
    {name:"application/x-pkcs7-certificates", icon:'' },
    {name:"application/pkcs7-mime", icon:'' },
    {name:"application/x-pkcs7-certreqresp", icon:'' },
    {name:"application/pkcs7-signature", icon:'' },
    {name:"application/vnd.powerbuilder6", icon:'' },
    {name:"image/x-portable-bitmap", icon: icon.__image },
    {name:"application/x-font-pcf", icon:'' },
    {name:"application/vnd.hp-pcl", icon:'' },
    {name:"application/vnd.hp-pclxl", icon:'' },
    {name:"image/x-pict", icon: icon.__image },
    {name:"application/vnd.curl.pcurl", icon:'' },
    {name:"image/x-pcx", icon: icon.__image },
    {name:"application/pdf", icon: icon.__pdf },
    {name:"application/font-tdpfr", icon:'' },
    {name:"image/x-portable-graymap", icon: icon.__image },
    {name:"application/x-chess-pgn", icon:'' },
    {name:"application/pgp-encrypted", icon:'' },
    {name:"application/pkixcmp", icon:'' },
    {name:"application/pkix-pkipath", icon:'' },
    {name:"application/vnd.3gpp.pic-bw-large", icon:'' },
    {name:"application/vnd.mobius.plc", icon:'' },
    {name:"application/vnd.pocketlearn", icon:'' },
    {name:"application/pls+xml", icon:'' },
    {name:"application/vnd.ctc-posml", icon:'' },
    {name:"image/png", icon: icon.__image },
    {name:"image/x-png", icon: icon.__image },
    {name:"image/vnd.mozilla.apng", icon: icon.__image },
    {name:"image/x-portable-anymap", icon: icon.__image },
    {name:"application/vnd.macports.portpkg", icon:'' },
    {name:"application/vnd.ms-powerpoint", icon: icon.__presentation },
    {name:"application/vnd.ms-powerpoint.template.macroenabled.12", icon: icon.__presentation },
    {name:"application/vnd.openxmlformats-officedocument.presentationml.template", icon: icon.__presentation },
    {name:"application/vnd.ms-powerpoint.addin.macroenabled.12", icon: icon.__presentation },
    {name:"application/vnd.cups-ppd", icon:'' },
    {name:"image/x-portable-pixmap", icon: icon.__image },
    {name:"application/vnd.ms-powerpoint.slideshow.macroenabled.12", icon: icon.__presentation },
    {name:"application/vnd.openxmlformats-officedocument.presentationml.slideshow", icon: icon.__presentation },
    {name:"application/vnd.ms-powerpoint.presentation.macroenabled.12", icon: icon.__presentation },
    {name:"application/vnd.openxmlformats-officedocument.presentationml.presentation", icon: icon.__presentation },
    {name:"application/vnd.lotus-freelance", icon:'' },
    {name:"application/pics-rules", icon:'' },
    {name:"application/vnd.3gpp.pic-bw-small", icon:'' },
    {name:"image/vnd.adobe.photoshop", icon: icon.__image },
    {name:"application/x-font-linux-psf", icon:'' },
    {name:"application/vnd.pvi.ptid1", icon:'' },
    {name:"application/x-mspublisher", icon:'' },
    {name:"application/vnd.3gpp.pic-bw-var", icon:'' },
    {name:"application/vnd.3m.post-it-notes", icon:'' },
    {name:"text/x-python", icon:'' },
    {name:"audio/vnd.ms-playready.media.pya", icon: icon.__audio },
    {name:"application/x-python-code", icon:'' },
    {name:"video/vnd.ms-playready.media.pyv", icon: icon.__video },
    {name:"application/vnd.epson.quickanime", icon:'' },
    {name:"application/vnd.intu.qbo", icon:'' },
    {name:"application/vnd.intu.qfx", icon:'' },
    {name:"application/vnd.publishare-delta-tree", icon:'' },
    {name:"application/vnd.quark.quarkxpress", icon:'' },
    {name:"audio/x-pn-realaudio", icon: icon.__audio },
    {name:"application/x-rar-compressed", icon: icon.__archive },
    {name:"application/vnd.rar", icon: icon.__archive },
    {name:"image/x-cmu-raster", icon: icon.__image },
    {name:"application/vnd.ipunplugged.rcprofile", icon:'' },
    {name:"application/rdf+xml", icon:'' },
    {name:"application/vnd.data-vision.rdz", icon:'' },
    {name:"application/vnd.businessobjects", icon:'' },
    {name:"application/x-dtbresource+xml", icon:'' },
    {name:"image/x-rgb", icon: icon.__image },
    {name:"application/reginfo+xml", icon:'' },
    {name:"application/resource-lists+xml", icon:'' },
    {name:"image/vnd.fujixerox.edmics-rlc", icon: icon.__image },
    {name:"application/resource-lists-diff+xml", icon:'' },
    {name:"application/vnd.rn-realmedia", icon:'' },
    {name:"audio/x-pn-realaudio-plugin", icon: icon.__audio },
    {name:"application/vnd.jcp.javame.midlet-rms", icon:'' },
    {name:"application/relax-ng-compact-syntax", icon:'' },
    {name:"application/x-rpm", icon:'' },
    {name:"application/vnd.nokia.radio-presets", icon:'' },
    {name:"application/vnd.nokia.radio-preset", icon:'' },
    {name:"application/sparql-query", icon:'' },
    {name:"application/rls-services+xml", icon:'' },
    {name:"application/rsd+xml", icon:'' },
    {name:"application/rss+xml", icon:'' },
    {name:"application/rtf", icon:'' },
    {name:"text/richtext", icon:'' },
    {name:"application/vnd.yamaha.smaf-audio", icon:'' },
    {name:"application/sbml+xml", icon:'' },
    {name:"application/vnd.ibm.secure-container", icon:'' },
    {name:"application/x-msschedule", icon:'' },
    {name:"application/vnd.lotus-screencam", icon:'' },
    {name:"application/scvp-cv-request", icon:'' },
    {name:"application/scvp-cv-response", icon:'' },
    {name:"text/vnd.curl.scurl", icon:'' },
    {name:"application/vnd.stardivision.draw", icon: icon.__archive },
    {name:"application/vnd.stardivision.calc", icon: icon.__archive },
    {name:"application/vnd.stardivision.impress", icon: icon.__archive },
    {name:"application/vnd.solent.sdkm+xml", icon:'' },
    {name:"application/sdp", icon:'' },
    {name:"application/vnd.stardivision.writer", icon: icon.__archive },
    {name:"application/vnd.seemail", icon:'' },
    {name:"application/vnd.sema", icon:'' },
    {name:"application/vnd.semd", icon:'' },
    {name:"application/vnd.semf", icon:'' },
    {name:"application/java-serialized-object", icon:'' },
    {name:"application/set-payment-initiation", icon:'' },
    {name:"application/set-registration-initiation", icon:'' },
    {name:"application/vnd.hydrostatix.sof-data", icon:'' },
    {name:"application/vnd.spotfire.sfs", icon:'' },
    {name:"application/vnd.stardivision.writer-global", icon: icon.__archive },
    {name:"text/sgml", icon:'' },
    {name:"application/x-sh", icon:'' },
    {name:"application/x-shar", icon:'' },
    {name:"application/shf+xml", icon:'' },
    {name:"text/vnd.wap.si", icon:'' },
    {name:"application/vnd.wap.sic", icon:'' },
    {name:"application/vnd.symbian.install", icon:'' },
    {name:"application/x-stuffit", icon:'' },
    {name:"application/x-stuffitx", icon:'' },
    {name:"application/vnd.koan", icon:'' },
    {name:"text/vnd.wap.sl", icon:'' },
    {name:"application/vnd.wap.slc", icon:'' },
    {name:"application/vnd.ms-powerpoint.slide.macroenabled.12", icon: icon.__presentation },
    {name:"application/vnd.openxmlformats-officedocument.presentationml.slide", icon: icon.__presentation },
    {name:"application/vnd.epson.salt", icon:'' },
    {name:"application/vnd.stardivision.math", icon: icon.__archive },
    {name:"application/smil+xml", icon:'' },
    {name:"application/x-font-snf", icon:'' },
    {name:"application/vnd.yamaha.smaf-phrase", icon:'' },
    {name:"application/x-futuresplash", icon:'' },
    {name:"text/vnd.in3d.spot", icon:'' },
    {name:"application/scvp-vp-response", icon:'' },
    {name:"application/scvp-vp-request", icon:'' },
    {name:"application/x-wais-source", icon:'' },
    {name:"application/sparql-results+xml", icon:'' },
    {name:"application/vnd.kodak-descriptor", icon:'' },
    {name:"application/vnd.epson.ssf", icon:'' },
    {name:"application/ssml+xml", icon:'' },
    {name:"application/vnd.sun.xml.calc.template", icon:'' },
    {name:"application/vnd.sun.xml.draw.template", icon:'' },
    {name:"application/vnd.wt.stf", icon:'' },
    {name:"application/vnd.sun.xml.impress.template", icon:'' },
    {name:"application/hyperstudio", icon:'' },
    {name:"application/vnd.ms-pki.stl", icon:'' },
    {name:"application/vnd.pg.format", icon:'' },
    {name:"application/vnd.sun.xml.writer.template", icon:'' },
    {name:"application/vnd.sus-calendar", icon:'' },
    {name:"application/x-sv4cpio", icon:'' },
    {name:"application/x-sv4crc", icon:'' },
    {name:"application/vnd.svd", icon:'' },
    {name:"image/svg+xml", icon: icon.__image },
    {name:"application/x-shockwave-flash", icon:'' },
    {name:"application/vnd.arastra.swi", icon:'' },
    {name:"application/vnd.sun.xml.calc", icon:'' },
    {name:"application/vnd.sun.xml.draw", icon:'' },
    {name:"application/vnd.sun.xml.writer.global", icon:'' },
    {name:"application/vnd.sun.xml.impress", icon:'' },
    {name:"application/vnd.sun.xml.math", icon:'' },
    {name:"application/vnd.sun.xml.writer", icon:'' },
    {name:"application/vnd.tao.intent-module-archive", icon: icon.__archive },
    {name:"application/x-tar", icon: icon.__archive },
    {name:"application/vnd.3gpp2.tcap", icon:'' },
    {name:"application/x-tcl", icon:'' },
    {name:"application/vnd.smart.teacher", icon:'' },
    {name:"application/x-tex", icon:'' },
    {name:"application/x-texinfo", icon:'' },
    {name:"application/x-tex-tfm", icon:'' },
    {name:"image/tiff", icon: icon.__image },
    {name:"application/vnd.tmobile-livetv", icon:'' },
    {name:"application/x-bittorrent", icon:'' },
    {name:"application/vnd.groove-tool-template", icon:'' },
    {name:"application/vnd.trid.tpt", icon:'' },
    {name:"application/vnd.trueapp", icon:'' },
    {name:"application/x-msterminal", icon:'' },
    {name:"text/tab-separated-values", icon:'' },
    {name:"application/x-font-ttf", icon:'' },
    {name:"application/vnd.simtech-mindmapper", icon:'' },
    {name:"application/vnd.genomatix.tuxedo", icon:'' },
    {name:"application/vnd.mobius.txf", icon:'' },
    {name:"application/vnd.ufdl", icon:'' },
    {name:"application/vnd.umajin", icon:'' },
    {name:"application/vnd.unity", icon:'' },
    {name:"application/vnd.uoml+xml", icon:'' },
    {name:"text/uri-list", icon:'' },
    {name:"application/x-ustar", icon: icon.__archive },
    {name:"application/vnd.uiq.theme", icon:'' },
    {name:"text/x-uuencode", icon:'' },
    {name:"application/x-cdlink", icon:'' },
    {name:"text/x-vcard", icon:'' },
    {name:"application/vnd.groove-vcard", icon:'' },
    {name:"text/x-vcalendar", icon:'' },
    {name:"application/vnd.vcx", icon:'' },
    {name:"application/vnd.visionary", icon:'' },
    {name:"video/vnd.vivo", icon: icon.__video },
    {name:"model/vrml", icon:'' },
    {name:"application/vnd.visio", icon:'' },
    {name:"application/vnd.vsf", icon:'' },
    {name:"model/vnd.vtu", icon:'' },
    {name:"application/voicexml+xml", icon:'' },
    {name:"application/x-doom", icon:'' },
    {name:"audio/x-wav", icon: icon.__audio },
    {name:"audio/wav", icon: icon.__audio },
    {name:"audio/x-ms-wax", icon: icon.__audio },
    {name:"image/vnd.wap.wbmp", icon: icon.__image },
    {name:"application/vnd.criticaltools.wbs+xml", icon:'' },
    {name:"application/vnd.wap.wbxml", icon:'' },
    {name:"application/vnd.ms-works", icon:'' },
    {name:"video/x-ms-wm", icon: icon.__video },
    {name:"audio/x-ms-wma", icon: icon.__audio },
    {name:"application/x-ms-wmd", icon:'' },
    {name:"application/x-msmetafile", icon:'' },
    {name:"text/vnd.wap.wml", icon:'' },
    {name:"application/vnd.wap.wmlc", icon:'' },
    {name:"text/vnd.wap.wmlscript", icon:'' },
    {name:"application/vnd.wap.wmlscriptc", icon:'' },
    {name:"video/x-ms-wmv", icon: icon.__video },
    {name:"video/x-ms-wmx", icon: icon.__video },
    {name:"application/x-ms-wmz", icon:'' },
    {name:"application/vnd.wordperfect", icon: icon.__document },
    {name:"application/vnd.ms-wpl", icon:'' },
    {name:"application/vnd.wqd", icon:'' },
    {name:"application/x-mswrite", icon:'' },
    {name:"application/wsdl+xml", icon:'' },
    {name:"application/wspolicy+xml", icon:'' },
    {name:"application/vnd.webturbo", icon:'' },
    {name:"video/x-ms-wvx", icon: icon.__video },
    {name:"application/vnd.hzn-3d-crossword", icon: icon.__document },
    {name:"application/x-silverlight-app", icon:'' },
    {name:"application/vnd.xara", icon:'' },
    {name:"application/x-ms-xbap", icon:'' },
    {name:"application/vnd.fujixerox.docuworks.binder", icon:'' },
    {name:"image/x-xbitmap", icon: icon.__image },
    {name:"application/vnd.syncml.dm+xml", icon:'' },
    {name:"application/vnd.adobe.xdp+xml", icon:'' },
    {name:"application/vnd.fujixerox.docuworks", icon:'' },
    {name:"application/xenc+xml", icon:'' },
    {name:"application/patch-ops-error+xml", icon:'' },
    {name:"application/vnd.adobe.xfdf", icon:'' },
    {name:"application/vnd.xfdl", icon:'' },
    {name:"application/xhtml+xml", icon:'' },
    {name:"image/vnd.xiff", icon: icon.__image },
    {name:"application/vnd.ms-excel", icon: icon.__spreadsheet },
    {name:"application/vnd.ms-excel.addin.macroenabled.12", icon: icon.__spreadsheet },
    {name:"application/vnd.ms-excel.sheet.binary.macroenabled.12", icon: icon.__spreadsheet },
    {name:"application/vnd.ms-excel.sheet.macroenabled.12", icon: icon.__spreadsheet },
    {name:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", icon: icon.__spreadsheet },
    {name:"application/vnd.ms-excel.template.macroenabled.12", icon: icon.__spreadsheet },
    {name:"application/vnd.openxmlformats-officedocument.spreadsheetml.template", icon: icon.__spreadsheet },
    {name:"application/xml", icon:'' },
    {name:"application/vnd.olpc-sugar", icon:'' },
    {name:"application/xop+xml", icon:'' },
    {name:"application/x-xpinstall", icon:'' },
    {name:"image/x-xpixmap", icon: icon.__image },
    {name:"application/vnd.is-xpr", icon:'' },
    {name:"application/vnd.ms-xpsdocument", icon: icon.__document },
    {name:"application/vnd.intercon.formnet", icon:'' },
    {name:"application/xslt+xml", icon:'' },
    {name:"application/vnd.syncml+xml", icon:'' },
    {name:"application/xspf+xml", icon:'' },
    {name:"application/vnd.mozilla.xul+xml", icon:'' },
    {name:"image/x-xwindowdump", icon: icon.__image },
    {name:"chemical/x-xyz", icon:'' },
    {name:"application/vnd.zzazz.deck+xml", icon:'' },
    {name:"application/zip", icon: icon.__archive },
    {name:"application/x-zip-compressed", icon: icon.__archive },
    {name:"application/zip-compressed", icon: icon.__archive },
    {name:"application/vnd.zul", icon:'' },
    {name:"application/vnd.handheld-entertainment+xml", icon:'' },
    {name:"image/x-adobe-dng", icon: icon.__image },
    {name:"image/x-sony-arw", icon: icon.__image },
    {name:"image/x-canon-cr2", icon: icon.__image },
    {name:"image/x-canon-crw", icon: icon.__image },
    {name:"image/x-kodak-dcr", icon: icon.__image },
    {name:"image/x-epson-erf", icon: icon.__image },
    {name:"image/x-kodak-k25", icon: icon.__image },
    {name:"image/x-kodak-kdc", icon: icon.__image },
    {name:"image/x-minolta-mrw", icon: icon.__image },
    {name:"image/x-nikon-nef", icon: icon.__image },
    {name:"image/x-olympus-orf", icon: icon.__image },
    {name:"image/x-pentax-pef", icon: icon.__image },
    {name:"image/x-fuji-raf", icon: icon.__image },
    {name:"image/x-panasonic-raw", icon: icon.__image },
    {name:"audio/flac", icon: icon.__audio },
    {name:"image/x-sony-sr2", icon: icon.__image },
    {name:"image/x-sony-srf", icon: icon.__image },
    {name:"image/x-sigma-x3f", icon: icon.__image} 
]

const types = Object.assign(mime.map(i=>{
                if (i.icon === '') i.icon = icon.__unknown 
                return i
            }).reduce((obj, i)=> Object.assign(obj, {[i.name]: i.icon})),

            {
                'folder': icon.__folder,
                'link': icon.__folder
            },
            {

            }
        )


export const type = {
    types,
    guess: (mime)=> types[mime] === undefined? icon.__unknown : types[mime]
    
}

export const misc = {
    upload: icon.__misc_upload,
    download: icon.__misc_download,
    show: icon.__misc_show,
    hide: icon.__misc_hide,
    add: icon.__misc_add,
    folder: icon.__misc_folder,
    arrow: icon.__misc_arrow,
}

